### ISSUE TITLE
/minecolonies resetsupplies, is not working

### ISSUE THREAD

**Issue by CriswellCodes** [kreezxil/World-of-Dragons-A-New-Age#63] opened 2019-11-16 17:48 UTC
Minecolonies version

Version: Minecolonies H3lay minecolonies-0.10.547-ALPHA-universal.jar

Expected behavior

I would expect that an Operator can reset the supply ship or camp of another player using the command appropriately.

Actual behavior

Join a game and Op yourself. Then try to reset the supply camp or ship of another player. Nothing occurs. Try as an Op to reset your own and it works successfully. At the moment a player can only reset their own camp while they are Op'd which would require Op permissions to be given to any player looking to reset their supplies.
Would love to see this command work where a Op can reset the camp/ship of any player on the server when needed.

Steps to reproduce the problem
1. Join a server with 2 or more people online
2. Op yourself
3. Reset your supply camp (this will work)
4. Attempt to reset a different players supply camp (This won't work)
5. Mission complete, GG

Crosslink:
https://github.com/ldtteam/minecolonies/issues/4080

**Comment by kreezxil** [comment] 2019-11-19 13:59
please check this in todays update of the pack

**Comment by kreezxil** [comment] 2019-11-24 19:02
i see they marked it as can't reproduce.

**Closed as completed by kreezxil** 2019-11-24 19:02 UTC
Labels: bug
